import { useState, useEffect } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { Terminal, Copy, RefreshCw, Check } from 'lucide-react';
import { writeText } from '@tauri-apps/plugin-clipboard-manager';
import { useAppStore } from '@/store/useAppStore';
import { getText } from '@/lib/i18n';
import { EnvInfo } from '@/types/monitor';
import { cn } from '@/lib/utils';

export function EnvFingerprint() {
  const { language } = useAppStore();
  const [data, setData] = useState<EnvInfo[]>([]);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const fetchData = async () => {
    setLoading(true);
    try {
      const res = await invoke<EnvInfo[]>('get_env_info');
      setData(res);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  // 挂载时加载一次
  useEffect(() => {
    fetchData();
  }, []);

  const handleCopyReport = async () => {
    const report = data.map(i => `- **${i.name}**: ${i.version}`).join('\n');
    const header = `### Dev Environment Report\nGenerated by CodeForge AI\n\n`;
    await writeText(header + report);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="h-full flex flex-col p-6 animate-in fade-in duration-300">
      
      {/* Toolbar */}
      <div className="flex justify-between items-center mb-6 shrink-0">
         <div className="text-sm text-muted-foreground">
            Detected {data.filter(i => i.version !== 'Not Found').length} tools
         </div>
         <div className="flex gap-2">
            <button 
                onClick={handleCopyReport}
                className="flex items-center gap-2 px-3 py-1.5 bg-secondary hover:bg-secondary/80 rounded-lg text-xs font-medium transition-colors"
            >
                {copied ? <Check size={14} className="text-green-500" /> : <Copy size={14} />}
                {getText('monitor', 'copyReport', language)}
            </button>
            <button 
                onClick={fetchData}
                disabled={loading}
                className="p-1.5 hover:bg-secondary rounded-lg transition-colors disabled:opacity-50"
            >
                <RefreshCw size={16} className={cn(loading && "animate-spin")} />
            </button>
         </div>
      </div>

      {/* Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 overflow-y-auto custom-scrollbar p-1">
         {data.map((item) => {
            const isInstalled = item.version !== 'Not Found';
            return (
                <div key={item.name} className="bg-card border border-border p-4 rounded-xl shadow-sm flex items-start gap-3 group hover:border-primary/30 transition-all">
                    <div className={cn("p-2 rounded-lg shrink-0", isInstalled ? "bg-primary/10 text-primary" : "bg-secondary text-muted-foreground")}>
                        <Terminal size={20} />
                    </div>
                    <div className="min-w-0 flex-1">
                        <div className="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-0.5">{item.name}</div>
                        <div className={cn("text-sm font-medium truncate", isInstalled ? "text-foreground" : "text-muted-foreground/50 italic")}>
                            {item.version}
                        </div>
                    </div>
                </div>
            )
         })}
         
         {/* 骨架屏 (Loading state) */}
         {loading && data.length === 0 && Array.from({length: 6}).map((_, i) => (
             <div key={i} className="bg-card border border-border p-4 rounded-xl shadow-sm flex gap-3 animate-pulse">
                 <div className="w-10 h-10 bg-secondary rounded-lg" />
                 <div className="flex-1 space-y-2 py-1">
                     <div className="h-3 bg-secondary rounded w-1/3" />
                     <div className="h-4 bg-secondary rounded w-2/3" />
                 </div>
             </div>
         ))}
      </div>
    </div>
  );
}